/*
 * Tencent is pleased to support the open source community by making TMagicEditor available.
 *
 * Copyright (C) 2023 THL A29 Limited, a Tencent company.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default {
  id: '75f0extui9d7yksklx27hff8xg',
  name: 'test',
  type: 'app',
  codeBlocks: {
    code_5336: {
      name: 'getData',
      content: ({ app, params }) => {
        console.log('this is getData function', params, app);
      },
      params: [
        {
          name: 'age',
        },
        {
          name: 'studentName',
        },
      ],
      comps: {},
    },
    code_5316: {
      name: 'getList',
      content: () => {
        console.log('this is getList function');
      },
      params: [],
      comps: {},
    },
  },
  items: [
    {
      type: 'page',
      id: 'page_299',
      name: 'index',
      title: '',
      layout: 'absolute',
      style: {
        position: 'relative',
        left: 0,
        top: 0,
        right: '',
        bottom: '',
        width: '100%',
        height: '100%',
        backgroundImage: '',
        backgroundColor: 'rgba(249, 249, 249, 1)',
        backgroundRepeat: 'no-repeat',
        backgroundSize: '100% 100%',
        color: 'rgba(30, 87, 176, 1)',
        fontSize: '',
        fontWeight: '',
        transform: {
          rotate: '',
          scale: '',
        },
      },
      events: [],
      created: {
        hookType: 'code',
        hookData: [
          {
            codeId: 'code_5336',
            params: {
              studentName: 'lisa',
              age: 14,
            },
          },
          {
            codeId: 'code_5316',
            params: {},
          },
        ],
      },
      items: [
        {
          type: 'overlay',
          id: 'overlay_2159',
          style: {
            position: 'fixed',
            width: '100%',
            height: '100%',
            top: 0,
            left: 0,
            backgroundColor: 'rgba(0, 0, 0, 0.8)',
          },
          name: '蒙层',
          items: [
            {
              type: 'container',
              id: 'container_607',
              style: {
                position: 'absolute',
                width: '80%',
                height: '400',
                top: '143.87',
                left: 37.5,
                right: '',
                bottom: '',
                backgroundImage: '',
                backgroundColor: 'rgba(255, 255, 255, 1)',
                backgroundRepeat: 'no-repeat',
                backgroundSize: '100% 100%',
                color: '',
                fontSize: '',
                fontWeight: '',
              },
              name: '组',
              items: [
                {
                  type: 'button',
                  id: 'button_7265',
                  style: {
                    position: 'absolute',
                    width: '270',
                    height: '37.5',
                    border: 0,
                    backgroundColor: '#fb6f00',
                    top: '322.71',
                    left: '15.99',
                    right: '',
                    bottom: '',
                    backgroundImage: '',
                    backgroundRepeat: 'no-repeat',
                    backgroundSize: '100% 100%',
                    color: '',
                    fontSize: '',
                    fontWeight: '',
                  },
                  name: '按钮',
                  text: '关闭弹窗',
                  multiple: true,
                  events: [
                    {
                      name: 'magic:common:events:click',
                      to: 'overlay_2159',
                      method: 'closeOverlay',
                    },
                  ],
                  created: [],
                },
                {
                  type: 'img',
                  id: 'img_3291',
                  style: {
                    position: 'absolute',
                    left: '63.94',
                    width: '176',
                    height: '176',
                    top: '105.91',
                  },
                  name: '图片',
                  src: 'https://puui.qpic.cn/vupload/0/1573555382625_bhp0wud8l6w.png/0',
                  url: '',
                },
                {
                  type: 'text',
                  id: 'text_8598',
                  style: {
                    position: 'absolute',
                    width: '86.92',
                    height: '37.97',
                    left: '106.90',
                    top: '35.97',
                    right: '',
                    bottom: '',
                    backgroundImage: '',
                    backgroundColor: '',
                    backgroundRepeat: 'no-repeat',
                    backgroundSize: '100% 100%',
                    color: '',
                    fontSize: '24',
                    fontWeight: '',
                  },
                  name: '文本',
                  text: 'Tmagic',
                  multiple: false,
                  events: [],
                  created: [],
                },
              ],
              layout: 'absolute',
              events: [],
              created: [],
            },
          ],
        },
        {
          id: 'container_d46a45cd',
          type: 'container',
          layout: 'absolute',
          style: {
            width: 375,
            height: '126',
            position: 'absolute',
            top: 0,
            left: 0,
            right: '',
            bottom: '',
            backgroundImage: '',
            backgroundColor: 'rgba(255, 255, 255, 1)',
            backgroundRepeat: 'no-repeat',
            backgroundSize: '100% 100%',
            color: '',
            fontSize: '',
            fontWeight: '',
            transform: {
              rotate: '',
              scale: '',
            },
          },
          name: '组',
          items: [
            {
              id: 'text_c00bd228',
              type: 'text',
              style: {
                width: 306,
                height: 26,
                color: 'rgba(34, 34, 34, 1)',
                'font-size': 20,
                position: 'absolute',
                top: 58,
                left: '16',
                right: '',
                bottom: '',
                backgroundImage: '',
                backgroundColor: '',
                backgroundRepeat: 'no-repeat',
                backgroundSize: '100% 100%',
                fontSize: '22',
                fontWeight: '500',
                transform: {
                  rotate: '',
                  scale: '',
                },
              },
              name: '文本',
              text: '于增补3名常委席位的意见投票',
              multiple: false,
              events: [],
              created: '',
              mounted: '',
            },
            {
              id: 'text_fafc6e58',
              type: 'text',
              style: {
                width: 311,
                height: 25,
                color: 'rgba(34, 34, 34, 1)',
                'font-size': 20,
                position: 'absolute',
                top: 24,
                left: '16',
                right: '',
                bottom: '',
                backgroundImage: '',
                backgroundColor: '',
                backgroundRepeat: 'no-repeat',
                backgroundSize: '100% 100%',
                fontSize: '22',
                fontWeight: '500',
                transform: {
                  rotate: '',
                  scale: '',
                },
              },
              name: '文本',
              text: '上海市衰老与退行性疾病学会关',
              multiple: false,
              events: [],
              created: '',
              mounted: '',
            },
            {
              id: 'label_4a02f9a7',
              type: 'label',
              style: {
                position: 'absolute',
                width: '78',
                height: '26',
                background: '#D2E4FF',
                'border-radius': '4',
                'font-size': 14,
                'line-height': 26,
                'text-align': 'center',
                top: 88,
                left: '16',
                right: '',
                bottom: '',
                backgroundImage: '',
                backgroundColor: 'rgba(210, 228, 255, 1)',
                backgroundRepeat: 'no-repeat',
                backgroundSize: '100% 100%',
                color: '',
                fontSize: '',
                fontWeight: '',
                transform: {
                  rotate: '',
                  scale: '',
                },
              },
              name: '标签按钮',
              text: '进行中',
              events: [],
              created: '',
              mounted: '',
            },
          ],
          'layout-scroll': '',
          events: [],
          created: '',
          mounted: '',
        },
        {
          id: 'button_802138b1',
          type: 'button',
          style: {
            width: '335',
            height: '60',
            border: 0,
            backgroundColor: '#1E57B0',
            'border-radius': '60',
            position: 'absolute',
            top: 545,
            left: 19,
            right: '',
            bottom: '',
            backgroundImage: '',
            backgroundRepeat: 'no-repeat',
            backgroundSize: '100% 100%',
            color: 'rgba(255, 255, 255, 1)',
            fontSize: '20',
            fontWeight: '',
            transform: {
              rotate: '',
              scale: '',
            },
          },
          name: '按钮',
          text: '确认投票',
          multiple: true,
          events: [],
          created: '',
          mounted: '',
        },
        {
          id: 'radiogroup_2f01d58d',
          type: 'radiogroup',
          style: {
            width: 338,
            height: 103,
            top: 141,
            left: 18,
            backgroundColor: '#fff',
            position: 'absolute',
            right: '',
            bottom: '',
            backgroundImage: '',
            backgroundRepeat: 'no-repeat',
            backgroundSize: '100% 100%',
            color: '',
            fontSize: '',
            fontWeight: '',
            transform: {
              rotate: '',
              scale: '',
            },
          },
          name: 'radioGroup',
          text: '医生章三',
          group: [
            {
              value: 'value1',
              radioName: '同意',
            },
            {
              value: 'value2',
              radioName: '不同意',
            },
            {
              value: 'value3',
              radioName: '弃权',
            },
          ],
          events: [],
          created: '',
          mounted: '',
          groupValue: 'doctor1',
        },
        {
          id: 'radiogroup_1546411d',
          type: 'radiogroup',
          style: {
            width: 338,
            height: 103,
            top: 266,
            left: 19,
            backgroundColor: '#fff',
            position: 'absolute',
            right: '',
            bottom: '',
            backgroundImage: '',
            backgroundRepeat: 'no-repeat',
            backgroundSize: '100% 100%',
            color: '',
            fontSize: '',
            fontWeight: '',
            transform: {
              rotate: '',
              scale: '',
            },
          },
          name: 'radioGroup',
          text: '医生王五',
          group: [
            {
              value: 'value3',
              radioName: '同意',
            },
            {
              value: 'value4',
              radioName: '不同意',
            },
            {
              value: 'value5',
              radioName: '弃权',
            },
          ],
          events: [],
          created: '',
          mounted: '',
          groupValue: 'doctor2',
        },
        {
          id: 'radiogroup_905761c2',
          type: 'radiogroup',
          style: {
            width: 338,
            height: 103,
            top: 391,
            left: 19,
            backgroundColor: '#fff',
            position: 'absolute',
            right: '',
            bottom: '',
            backgroundImage: '',
            backgroundRepeat: 'no-repeat',
            backgroundSize: '100% 100%',
            color: '',
            fontSize: '',
            fontWeight: '',
            transform: {
              rotate: '',
              scale: '',
            },
          },
          name: 'radioGroup',
          text: '医生李四',
          group: [
            {
              value: 'value7',
              radioName: '同意',
            },
            {
              value: 'value8',
              radioName: '不同意',
            },
            {
              value: 'value9',
              radioName: '弃权',
            },
          ],
          events: [],
          created: '',
          mounted: '',
          groupValue: 'doctor3',
        },
      ],
      mounted: '',
    },
  ],
};
